


p 'Welcome to CoNnEcT fOoOoUr!'
p 'The wacky contest vertical, horizontal, and diagonal domination are the name of the game!'
p 'May the odds be eve in your favor!'

print "ABCDEFG
.......
.......
.......
.......
.......
......." #not sure how to get rid of modulo here