require './lib/game'
require './lib/board'


p 'Welcome to CoNnEcT fOoOoUr!'
p 'The wacky contest where vertical, horizontal, and diagonal domination are the name of the game!'
p 'May the odds be ever in your favor!'

puts "ABCDEFG
.......
.......
.......
.......
.......
......."
